stages:
  - test
  - publish
build-and-publish-proxy:
  image:
    entrypoint:
      - ""
    name: gcr.io/kaniko-project/executor:debug
#  only:
#    refs:
#      # We only enable publishing to the public repo on master, to avoid unwanted version of branches to end up there
#      # Theoretically we could publish branches there aswell, but I feel the risk of accidentally publishing something
#      # which contains secrets for example does not outweigh the convenience.
#      - main
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"quay.io\":{\"username\":\"${quay_user}\",\"password\":\"${quay_password}\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context "./proxy/"  --dockerfile ./proxy/Dockerfile --destination quay.io/stackstate/http-header-injector-proxy:sha-${CI_COMMIT_SHORT_SHA}
  stage: publish

build-and-publish-proxy-init:
  image:
    entrypoint:
      - ""
    name: gcr.io/kaniko-project/executor:debug
#  only:
#    refs:
#      # We only enable publishing to the public repo on master, to avoid unwanted version of branches to end up there
#      # Theoretically we could publish branches there aswell, but I feel the risk of accidentally publishing something
#      # which contains secrets for example does not outweigh the convenience.
#      - main
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"quay.io\":{\"username\":\"${quay_user}\",\"password\":\"${quay_password}\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context "./proxy/"  --dockerfile ./proxy/Dockerfile --destination quay.io/stackstate/http-header-injector-proxy:sha-${CI_COMMIT_SHORT_SHA}
  stage: publish

validate-http-header-injector-branch:
  image: quay.io/helmpack/chart-testing:v3.6.0
  before_script:
    - .gitlab/validate_before_script.sh
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: never
    - when: always
  script:
    - ct lint --debug --validate-maintainers=false --check-version-increment=true --config ct.yaml
    - helm template charts/http-header-injector | kubeconform  -
  stage: test

publish-http-header-injector-branch:
  image: ${DOCKER_PROXY_URL}/stackstate/sts-ci-images:stackstate-devops-0ccefe18
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
  script:
    - helm cm-push --username ${CHARTMUSEUM_INTERNAL_USERNAME} --password ${CHARTMUSEUM_INTERNAL_PASSWORD} charts/http-header-injector ${CHARTMUSEUM_INTERNAL_URL}
  stage: publish
  variables:
    CHART: charts/http-header-injector

publish-http-header-injector:
  image: ${DOCKER_PROXY_URL}/stackstate/sts-ci-images:stackstate-devops-0ccefe18
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - when: never
  script:
    - helm cm-push --username ${CHARTMUSEUM_USERNAME} --password ${CHARTMUSEUM_PASSWORD} charts/http-header-injector ${CHARTMUSEUM_URL}
  stage: publish
