apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "http-header-injector.cert-serviceaccount.name" . }}"
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-delete,post-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: "{{ include "http-header-injector.app.name" . }}"
