apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ include "http-header-injector.cert-serviceaccount.name" . }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-delete,post-upgrade
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ include "http-header-injector.cert-clusterrole.name" . }}"
subjects:
  - kind: ServiceAccount
    name: "{{ include "http-header-injector.cert-serviceaccount.name" . }}"
    namespace: {{ .Release.Namespace }}
