{{- if eq .Values.webhook.tls.mode "cert-manager" }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "http-header-injector.webhook-service.name" . }}
  {{- if eq .Values.webhook.tls.certManager.issuerKind "ClusterIssuer" }}
  namespace: {{ .Release.Namespace }}}
  {{- else }}
  namespace: {{ .Values.webhook.tls.certManager.issuerNamespace | required "issuerNamespace is required when issuerKind is not ClusterIssuer" }}
  {{- end }}
  labels:
    app.kubernetes.io/component: http-header-injector
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "http-header-injector.app.name" . }}
spec:
  secretName: {{ include "http-header-injector.cert-secret.name" . }}
  issuerRef:
    name: {{ .Values.webhook.tls.certManager.issuer }}
    kind: {{ .Values.webhook.tls.certManager.issuerKind }}
  dnsNames:
  - "{{ include "http-header-injector.webhook-service.name" . }}"
  - "{{ include "http-header-injector.webhook-service.name" . }}.{{ .Release.Namespace }}"
  - "{{ include "http-header-injector.webhook-service.name" . }}.{{ .Release.Namespace }}.svc"
{{- end }}
