apiVersion: v1
kind: Service
metadata:
  name: "{{ include "http-header-injector.webhook-service.name" . }}"
spec:
  ports:
    - port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: "{{ include "http-header-injector.app.name" . }}"
