apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: http-server
  name: http-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        http-header-injector.stackstate.io/inject: enabled
        http-header-injector-debug.stackstate.io/inject: enabled
      labels:
        app: http-server
      name: http-server
    spec:
      containers:
        - args:
            - -text=apple
          image: hashicorp/http-echo
          name: http-server
          ports:
            - containerPort: 5678
              name: web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: http-server
spec:
  ports:
    - port: 5678
      protocol: TCP
      targetPort: 5678
  selector:
    app: http-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: http-client
  name: http-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-client
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        http-header-injector.stackstate.io/inject: enabled
        http-header-injector-debug.stackstate.io/inject: enabled
      labels:
        app: http-client
      name: http-client
    spec:
      containers:
        - env:
            - name: URL
              value: http://http-server:5678/index.html
            - name: INTERVAL
              value: "2"
          image: julianosk/continuous-requests-py:1.2
          name: http-client
        - image: curlimages/curl
          name: curl
          command: ["/bin/sh", "-c", "while echo \"Running\"; do sleep 1; done"]
